print("addition : ",2+3)
print("substraction : ",3+9)
print("multiplication : ",3*8)
print("division : ",10/2)
print("floor division : ",10//2)
print("modular division : ",10%3)
print("power of : ", 3**4)